version: '2'
services:
  web_201:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "8480:8080"
  db_202:
    image: opavlova/db-mysql:5.5
    ports:
      - "3606:3306"
  web_203:
    image: tomee
    ports:
      - "8481:8080"
