version: '2'
services:
  web:
    environment:
      TESTING: 'true'
    ports:
          - "8084:8080"
  web_tomee1:
    build:
      context: ./build-dir
      dockerfile: Dockerfile2
    environment:
      DEBUG: 'true'
  web_tomee2:
      build:
        context: ./build-dir
        dockerfile: Dockerfile2
