version: '2'
services:
  web_tomcat_simple1:
    image: opavlova/tomee
    ports:
      - "8101:8080"
  db_mysql_simple:
    image: opavlova/db-mysql:5.5
    ports:
      - "3000:3306"
#connection url jdbc:mysql://localhost:3336/DOCKERDB
