version: '2'
services:
  web_tomcat:
    environment:
       TAG_TOMCAT1: '9-jre8'
    env_file:
      - .env
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "9189:8080"

  db_mysql:
    image: "opavlova/db-mysql:${TAG_MYSQL_FROM_ENVFILE}"
    ports:
      - "4409:3306"
#connection url jdbc:mysql://localhost:4409/DOCKERDB
