services:
  php82:
    build:
      context: .
    container_name: php82_swoole
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
    restart: always
    tty: true
    cap_add:
      - SYS_PTRACE