version: '2'
services:
  web:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "8301:8080"
  db:
    image: opavlova/db-mysql:5.5
    ports:
      - "8302:3306"
#connection url jdbc:mysql://localhost:3307/DOCKERDB
