version: "2"
services:
  web1:
    image: tomcat:7.0.82-jre7
    ports:
      - 8144:8080
  web2:
    image: tomcat:7.0-jre7
    ports:
      - 8145:8080
  web3:
    image: tomcat:7-jre7
    ports:
      - 8146:8080
  web4:
    image: tomcat:7.0.82
    ports:
      - 8147:8080
  web5:
    image: tomcat:7.0
    ports:
      - 8148:8080
  web6:
    image: tomcat:7
    ports:
      - 8149:8080
  web7:
    image: jboss/wildfly:10.0.0.Final
    ports:
      - 8150:8080
  web8:
    image: tomcat:7-alpine
    ports:
      - 8151:8080
  web9:
    image: tomcat:7.0-alpine
    ports:
      - 8152:8080
  web10:
    image: tomcat:7.0.82-alpine
    ports:
      - 8153:8080
  web11:
    image: tomcat:7-jre7-alpine
    ports:
      - 8154:8080
  web12:
    image: tomcat:7.0-jre7-alpine
    ports:
      - 8155:8080
  web13:
    image: tomcat:7.0.82-jre7-alpine
    ports:
      - 8156:8080
  web14:
    image: tomcat:7.0.82-jre8
    ports:
      - 8157:8080
  web15:
    image: tomcat:7.0-jre8
    ports:
      - 8158:8080
  web16:
    image: tomcat:7-jre8
    ports:
      - 8159:8080
  web17:
    image: tomcat:7.0.82-jre8-alpine
    ports:
      - 8160:8080
  web18:
    image: tomcat:7.0-jre8-alpine
    ports:
      - 8098:8080
  web19:
    image: tomcat:7-jre8-alpine
    ports:
      - 8099:8080
  web20:
    image: tomcat:8.0.48-jre7
    ports:
      - 8100:8080
  web21:
    image: tomcat:8.0-jre7
    ports:
      - 8101:8080
  web22:
    image: tomcat:8.0.48
    ports:
      - 8102:8080
  web23:
    image: tomcat:8.0
    ports:
      - 8103:8080
  web24:
    image: tomcat:8.0.48-jre7-alpine
    ports:
      - 8104:8080
  web25:
    image: tomcat:8.0-jre7-alpine
    ports:
      - 8105:8080
  web26:
    image: tomcat:8.0.48-alpine
    ports:
      - 8106:8080
  web27:
    image: tomcat:8.0-alpine
    ports:
      - 8107:8080
  web28:
    image: tomcat:8.0.48-jre8
    ports:
      - 8108:8080
  web29:
    image: tomcat:8.0-jre8
    ports:
      - 8109:8080
  web30:
    image: tomcat:8.0.48-jre8-alpine
    ports:
      - 8110:8080
  web31:
    image: tomcat:8.0-jre8-alpine
    ports:
      - 8111:8080
  web32:
    image: tomcat:8.5.24-jre8
    ports:
      - 8112:8080
  web33:
    image: tomcat:8.5-jre8
    ports:
      - 8113:8080
  web34:
    image: tomcat:8-jre8
    ports:
      - 8114:8080
  web35:
    image: tomcat:jre8
    ports:
      - 8115:8080
  web36:
    image: tomcat:8.5.24
    ports:
      - 8116:8080
  web37:
    image: tomcat:8.5
    ports:
      - 8117:8080
  web38:
    image: tomcat:8
    ports:
      - 8118:8080
  web39:
    image: tomcat:8.5.24-jre8-alpine
    ports:
      - 8119:8080
  web40:
    image: tomcat:8.5-jre8-alpine
    ports:
      - 8120:8080
  web41:
    image: tomcat:8-jre8-alpine
    ports:
      - 8121:8080
  web42:
    image: tomcat:jre8-alpine
    ports:
      - 8122:8080
  web43:
    image: tomcat:8.5.24-alpine
    ports:
      - 8123:8080
  web44:
    image: tomcat:8.5-alpine
    ports:
      - 8124:8080
  web45:
    image: tomcat:8-alpine
    ports:
      - 8125:8080
  web46:
    image: tomcat:alpine
    ports:
      - 8126:8080
  web47:
    image: tomcat:9.0.2-jre8
    ports:
      - 8127:8080
  web48:
    image: tomcat:9.0-jre8
    ports:
      - 8128:8080
  web49:
    image: tomcat:9-jre8
    ports:
      - 8129:8080
  web50:
    image: tomcat:9.0.2
    ports:
      - 8130:8080
  web51:
    image: tomcat:9.0
    ports:
      - 8131:8080
  web52:
    image: tomcat:9
    ports:
      - 8132:8080
  web53:
    image: glassfish:4.1-jdk8
    ports:
      - 8133:8080
  web54:
    image: glassfish:4.1
    ports:
      - 8134:8080
  web55:
    image: glassfish:4.0
    ports:
      - 8135:8080
  web56:
    image: glassfish:4.0-jdk7
    ports:
      - 8136:8080
  web57:
    image: jboss/wildfly:9.0.1.Final
    ports:
      - 8137:8080
  web58:
    image: jboss/wildfly:8.1.0.Final
    ports:
      - 8138:8080
  web59:
    image: jboss/wildfly:9.0.0.Final
    ports:
      - 8139:8080
  web60:
    image: jboss/wildfly:8.2.1.Final
    ports:
      - 8140:8080
  web61:
    image: jboss/wildfly:10.1.0.Final
    ports:
      - 8141:8080
  web62:
    image: jboss/wildfly:9.0.2.Final
    ports:
      - 8142:8080
  web63:
    image: jboss/wildfly:11.0.0.Final
    ports:
      - 8143:8080



