version: '2'
services:
  web_101:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "190:8080"
  db_102:
    image: opavlova/db-mysql:5.5
    ports:
      - "334:3306"
  web_103:
    image: tomee
    ports:
      - "191:8080"
