version: '2'
services:
  web:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "1820:8080"
  db:
    image: opavlova/db-mysql:5.5
    ports:
      - "3333:3306"
#connection url jdbc:mysql://localhost:3308/DOCKERDB
