version: '2'
services:

  web_201:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    command: echo 'scaled'
    scale: 3


  db_201:
    image: opavlova/db-mysql:5.5
    container_name: ttt_1.2-3_test




