version: '2'
services:
  web_tomcat:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "9289:8080"
  db_mysql:
    image: "opavlova/db-mysql:${TEST_ENV_TAG_MYSQL_FROM_FIELD}"
    ports:
      - "4409:3306"
#connection url jdbc:mysql://localhost:4409/DOCKERDB
