#version: "3.8"
services:
  #============================================================//
  #   "Secrets" top level option and its options
  #============================================================//
  #  TODO https://docs.docker.com/compose/compose-file/09-secrets/
  #  issue https://youtrack.jetbrains.com/issue/IJPL-155810/DockerCompose.-Editor.-Support-secrets.environment-key
  test1:
    image: busybox
    secrets:
      - secret1-cert
      - secret2-token


secrets:
  secret1-cert:
    file: ./server.cert
  secret2-token:
    environment: "OAUTH_TOKEN"