version: '2'
services:
  web:
    build:
      context: ./build-dir
      dockerfile: Dockerfile1
    ports:
      - "18080:8080"
  db:
    image: opavlova/db-mysql:5.5
    ports:
      - "3306:3306"
#connection url jdbc:mysql://localhost:3306/DOCKERDB
