web:
  ports:
      - "8085:8080"
  environment:
    PRODUCTION: 'true'
web_tomee:
  build:
    context: ./build-dir
    dockerfile: Dockerfile2
  ports:
    - "8086:8080"
  environment:
    DEBUG: 'true'