version: '2'
services:
  web_101:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
  db_102:
    image: opavlova/db-mysql:5.5
    ports:
      - "3406:3306"
  web_103:
    image: tomee
    ports:
      - "8181:8080"
