version: '2'
services:
  web_tomcat:
    build:
      context: ./build-dir
      dockerfile: Dockerfile
    ports:
      - "1822:8080"
  db_mysql:
    image: opavlova/db-mysql:5.5
    ports:
      - "3335:3306"
#connection url jdbc:mysql://localhost:3308/DOCKERDB
