version: '2.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-alternate
      network: ddd
    networks:
      - new
      - outside
      - new:
          - test1
      - app_net_1:
          - test2

networks:
  outside:
#  OK:  name: Not supported for version 2 docker-compose files. Use network_mode instead.
      external: true
  new:
  app_net_1:
  app_net_2:
  app_net_3: