version: '3.8'
# TODO issue https://youtrack.jetbrains.com/issue/IJPL-67737/Docker-compose-include-property-not-recognized
include:
  - my-compose-include.yaml  #with serviceB declared
services:
  serviceA:
    image: busybox
    depends_on:
      - serviceB