version: '2'
services:
  web:
    ports:
        - "8082:8080"
    environment:
      PRODUCTION: 'true'
  web_tomee:
    build:
      context: ./build-dir
      dockerfile: Dockerfile2
    ports:
      - "8083:8080"
    environment:
      DEBUG: 'true'
  db:
    ports:
      - "13306:3306"
    environment:
      PRODUCTION: 'true'
  #connection url jdbc:mysql://localhost:13306/DOCKERDB